### ISSUE TITLE
Allow multiple hosted zones on the same domain name

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#1085]
so the route53 module has an issue where Amazon does allow multiple hosted zones for the same domain name, but we assumed they did not, and the module currently breaks in a way that prevents `iasql_apply()` from working for any module.

**Comment by mtp1376** [comment]
So the entityId should be changed, because currently there might be the same ids for multiple resources.
```
entityId = (e: ResourceRecordSet) => `${e.recordType}|${e.name}`;
```
This makes the comparator function unable to effectively compare resources, and will result in some resources to not be synced when running `sync()` (just checked sync logic, but are logics are definitely affected).
This ignorance of the same resources happens despite changing the table schema from
```node
@Unique('UQ_name__record_type', ['name', 'recordType'])
```
to
```node
@Unique('UQ_name__record_type', ['parentHostedZone', 'name', 'recordType'])
```
which initially throw exceptions upon creation of the (wrongly-assumed) same resources.

**Comment by aguillenv** [comment]
hmmm I know I did not allow it at the time I wrote the module, but I'm not sure if at some point in time @dfellis fixed this? because the entity does not have the `unique` constraint 🤔 https://github.com/iasql/iasql-engine/blob/main/src/modules/0.0.19/aws_route53_hosted_zones/entity/hosted_zone.ts

Or maybe I'm missing out something 😅

**Comment by mtp1376** [comment]
> hmmm I know I did not allow it at the time I wrote the module, but I'm not sure if at some point in time @dfellis fixed this? because the entity does not have the `unique` constraint 🤔 https://github.com/iasql/iasql-engine/blob/main/src/modules/0.0.19/aws_route53_hosted_zones/entity/hosted_zone.ts
> 
> Or maybe I'm missing out something 😅

Clearly not fixed yet. Check [here](https://github.com/iasql/iasql-engine/blob/main/src/modules/0.0.19/aws_route53_hosted_zones/entity/resource_records_set.ts#L22), but the logic in different areas show the same thing.

**Comment by aguillenv** [comment]
ohh I see!
