### ISSUE TITLE
Research How Terraform is Handling JSON Policies

### ISSUE THREAD

**Issue by mtp1376** [iasql/iasql-engine#1137]
We can check how Terraform or other IaC apps are detecting the changes in JSON Policies and how are they checking if two policies are the same thing.
We can read their codes to gain an understanding of their logic.

**Comment by mtp1376** [comment]
OK seems this issue with the AWS API has been known. Terraform has these checks for it:
- [This one](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/verify/json.go#L17) which itself has a call to:
   - [This one](https://github.com/hashicorp/awspolicyequivalence/blob/v1.6.0/aws_policy_equivalence.go#L23-L33)

The overall logic can be translated to TypeScript and I think this can help us find a way to handle it properly.

**Comment by dfellis** [comment]
Examples of our current ad-hoc handling of this issue are:

- [ECR](https://github.com/iasql/iasql-engine/blob/main/src/modules/0.0.18/aws_ecr/index.ts#L299-L318)
- [IAM](https://github.com/iasql/iasql-engine/blob/main/src/modules/0.0.18/aws_iam/index.ts#L124-L151)
- [RDS](https://github.com/iasql/iasql-engine/blob/main/src/modules/0.0.18/aws_rds/index.ts#L361-L385) (sort of, not a policy doc per se, but a similar issue)
- [S3](https://github.com/iasql/iasql-engine/blob/main/src/modules/0.0.18/aws_s3/index.ts#L21) (not actually dealing with the issue, the module and its tests are just too simple to run into problems, yet)
- [VPC](https://github.com/iasql/iasql-engine/blob/main/src/modules/0.0.18/aws_vpc/mappers/endpoint_gateway.ts#L23-L25) (also just haven't run into the issues, yet, because we're not stretching this in the test suite for this module)
