### ISSUE TITLE
If attaching an invalid/nonexistent arn policy to a `role`, apply loops forever trying to update the entity

### ISSUE THREAD

**Issue by depombo** [iasql/iasql-engine#1256]

**Comment by aguillenv** [comment]
@depombo do you have a specific case for this? I have tested creating a role and passing a malformed arn or an arn that does not exist and it does loop a couple of times trying to update but then it fails "successfully" if that makes sense. Maybe the behaviour can be changed so that if it fails to attach an arn, we ignore it, but still attached the ones from the list that exists? Because right now if I have a list ['good-arn', 'bad-arn'] it will fail due to the bad-arn and it will not attach anything.

**Comment by depombo** [comment]
interesting, for me it failed completely. maybe how the arn was malformed matters? what malformed arn did you try to pass? I think I passed `'arn:aws:iam::aws:policy/AWSAppRunnerServicePolicyForECRAccess'` instead of `'arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess'`

**Comment by aguillenv** [comment]
But when you mean "for me it failed completely", does that means an infinite loop without failure?

I have tried with `arn:aws:iam::aws:policy/service-role/AmazonECZTaskExecutionRolePolicy` instead of `arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy` (changed the S for a Z in ECS). Also tried with `fake/arn`. The result was 2 iterations trying to update and then this failure: `IamRole cloud update error: Policy arn:aws:iam::aws:policy/service-role/AmazonECZTaskExecutionRolePolicy does not exist or is not attachable.`

**Comment by depombo** [comment]
was this on update or creation? I think this happened once the role was already created and I was updating the arns

**Comment by aguillenv** [comment]
Same result doing an update `IamRole cloud update error: Policy arn:aws:iam::aws:policy/AmazonEC2ContainerServiceforEC2Role does not exist or is not attachable.`

My test was creating a role with `['arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy']` and update it with `['arn:aws:iam::aws:policy/AmazonEC2ContainerServiceforEC2Role']` instead of `['arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role']` (removing the `service-role`part from the arn as in your example).

Maybe it was just taking too long? we have a waiter with 900 seconds waiting the policies are attached. For my tests I have reduced that wait time but nothing else.

**Comment by depombo** [comment]
It sounds like the issue is not there anymore so let's close this out. It could be that it was before I added the waiters
