### ISSUE TITLE
Throwing error on disconnect when it actually worked

### ISSUE THREAD

**Issue by aguillenv** [iasql/iasql-engine#717]

**Comment by aguillenv** [comment]
```
Error: User with ID <userid> has no IaSQL database with alias <dbalias>
```

**Comment by aguillenv** [comment]
I think is possible, didn't try it though. But, it is also happening something like this in the tests suite, right?

**Comment by aguillenv** [comment]
> > I think is possible, didn't try it though. But, it is also happening something like this in the tests suite, right?
> 
> I don't recall seeing _this_ bug in the test suite. Other race condition bugs, yes, but not that disconnecting the DB failed because it didn't exist.

https://github.com/iasql/iasql-engine/runs/6265778149?check_suite_focus=true

**Comment by dfellis** [comment]
That's not the exact same error, but I see where it's coming from: https://github.com/iasql/iasql-engine/runs/6265778149?check_suite_focus=true#step:5:6799

The scheduler didn't actually shut down before the database was deleted, and then it triggered an error on the `/disconnect` endpoint since it threw those errors before the response returned.

That should be a quick fix (we're either not `await`ing the scheduler shutdown properly, or we are, there's a bug in *that*, but we can fix it by literally inserting a `sleep` for a second or two).

**Comment by dfellis** [comment]
Thankfully, it looks like we don't need to follow the `sleep` path. I think we caused this ourselves by using the event emitter pattern: https://github.com/iasql/iasql-engine/blob/main/src/services/scheduler.ts#L127-L140

You can't `await` on the event handlers (by design) so the call to `stop` can't tell when it's actually stopped.

The fact that this *usually* works tells me that it shuts down *really* quickly.
